### ISSUE TITLE
MapData coming up empty

### ISSUE THREAD

**Issue by innerspirit** [msikma/screp-js-wrapper#1]
Hi, it seems that some of the data is always empty/null when calling this library. I was using screptools/packages/file/index before (which calls screp directly) and the mapData values were coming up, but once I replaced it with this one that started erroring out. Commands is also null. There's also some 'undefined: undefined' stuff in my debugger's output.

The same happens with all the replays that I tested.

```
{Header: {…}, Commands: null, MapData: null, Computed: {…}}
Commands:null
Computed:{LeaveGameCmds: Array(1), ChatCmds: Array(5), WinnerTeam: 1, PlayerDescs: Array(2), undefined: undefined}
ChatCmds:(5) [{…}, {…}, {…}, {…}, {…}]
LeaveGameCmds:(1) [{…}]
PlayerDescs:(2) [{…}, {…}]
undefined:undefined
WinnerTeam:1
__proto__:Object
Header:{Engine: {…}, Frames: 33469, StartTime: Sat May 07 2022 11:14:36 GMT-0300 (Argentina Standard Time), Title: 'oafRZgPLHXpg', undefined: undefined, …}
AvailSlotsCount:2
Engine:{Name: 'Brood War', ID: 1, ShortName: 'BW'}
Frames:33469
Host:'PrG)Sabb4th'
Map:'GOOD NIGHT 1.31'
MapHeight:128
MapWidth:128
Players:(2) [{…}, {…}]
Speed:{Name: 'Fastest', ID: 6}
StartTime:Sat May 07 2022 11:14:36 GMT-0300 (Argentina Standard Time)
SubType:1
Title:'oafRZgPLHXpg'
Type:{Name: 'Top vs Bottom', ID: 15, ShortName: 'TvB'}
undefined:undefined
__proto__:Object
MapData:null
__proto__:Object
```

**Comment by msikma** [comment]
Hi there. First of all, sorry for replying so late. First of all I would recommend that you use [screp-js](https://github.com/msikma/screp-js) instead, as this package isn't really meant to be used directly. The output will be slightly different from what you expect.

This package is still a bit experimental and I haven't added tests yet, so there might still be some edge cases.

I'm not sure why you aren't getting all the data. By default, screp does not include all data in its output, but this wrapper package should explicitly get all data. If you're using [screp-js](https://github.com/msikma/screp-js), you need to configure it to include all data in its output, just like with the regular screp tool. You can do this like the following:

```js
const res = await Screp.parseBuffer(ui8, {
  mapData: true,
  mapTiles: true,
  mapResLoc: true,
  cmds: true
})
```

(Or in your case you might want to use [screp-js-file](https://github.com/msikma/screp-js-file) so you don't manually have to create a buffer and convert it to uint8array.)

This results in the following data:

```js
{
  Header: {
    Engine: { Name: 'Brood War', ID: 1, ShortName: 'BW' },
    Frames: 13952,
    StartTime: 2021-07-17T16:08:00.000Z,
    Title: 'u5',
    undefined: undefined,
    MapWidth: 128,
    MapHeight: 128,
    AvailSlotsCount: 4,
    Speed: { Name: 'Fastest', ID: 6 },
    Type: { Name: 'Top vs Bottom', ID: 15, ShortName: 'TvB' },
    SubType: 2,
    Host: 'Zmanryan',
    Map: '| iCCup | Fighting Spirit ',
    Players: [ [Object], [Object] ]
  },
  Commands: {
    Cmds: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 3100 more items
    ],
    ParseErrCmds: null,
    undefined: undefined
  },
  MapData: {
    Version: 205,
    TileSet: { Name: 'Jungle', ID: 4 },
    Name: '| iCCup | Fighting Spirit 1.3',
    Description: 'Green Tea, want some?\r\n' +
      'Created by Rose.of.Dream.     \r\n' +
      'Presented by Kespa\r\n' +
      '[ www.iccup.com ] modification',
    Tiles: [
        288,   304,  3744,  3760,  3714,  3730,  3650,  3666, 3681,
       3697,  3746,  3762,  3681,  3697,  3745,  3761,  3968, 3984,
       3904,  3920,  3680,  3696,  3744,  3760,  3968,  3984,  644,
        660,   675, 19568, 19568,   629,  1508,  1524,  1476, 1492,
        580,   596,  3906,  3922,  3681,  3697,  3746,  3762, 3682,
       3698,  3745,  3761,  3714,  3730,    68,    84,  3873, 3889,
       4097,  4113,  3777,  3793,  3808,  3824, 18256, 18257,  644,
        660,   996, 19840,  1801,  1817,  2146,  2162,    96,  112,
      21120, 21121, 21122, 21123, 21124, 21125,  1929,  1945, 1891,
       1907,  1986,  2002,  2019,  2035,  1931,  1947,  1891, 1907,
       9093,  9109,   736,   752,  1089,  1105,    65,    81,   69,
         85,
      ... 16284 more items
    ],
    MineralFields: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 8 more items
    ],
    Geysers: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    StartLocations: [ [Object], [Object], [Object], [Object] ],
    undefined: undefined
  },
  Computed: {
    LeaveGameCmds: [ [Object] ],
    ChatCmds: null,
    WinnerTeam: 2,
    PlayerDescs: [ [Object], [Object] ],
    undefined: undefined
  }
}
```

I see the `undefined: undefined` items in there and will be fixing that!

**Comment by msikma** [comment]
I've updated screp-js and screp-js-file to 0.2.1. The `undefined: undefined` problem should be fixed. They also now have tests. Maybe you can give it a try to see if this helps. Follow the documentation in screp-js to get full output (without things like `MapData` being null, etc.)

screptools is still not using the newer version, but I'll be updating that in the future. That one is very much a more specific project, less generic as this.

**Comment by innerspirit** [comment]
Thanks, I'm not sure why I put the issue here, might have been a mistake or maybe I thought it was more appropriate since the Go code is here.

Anyway the undefined issue is gone, but the missing data issue remains. I'm calling screptools-process's method processRepData with this data and it throws a lot of errors. I'm going to try processing the data directly instead of using that and see if there's enough data.

**Comment by msikma** [comment]
> Anyway the undefined issue is gone, but the missing data issue remains.

Does it still remain even if you pass an options object?

Like this:

```js
Screp.parseBuffer(buffer, {mapData: true, mapTiles: true, mapResLoc: true, cmds: true})
```

**Comment by innerspirit** [comment]
That worked! To be clear I was using screp-js-file, and now I am able to bypass embedding screp itself into my thing, thanks!

**Comment by msikma** [comment]
Awesome, glad it works. Let me know if you run into any other issues.
